version: "3"
services:
  server:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - server_public:/app/public
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
    container_name: voting-server
    user: "root:root"
  db:
    image: mysql
    build:
      context: ./database
      dockerfile: Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "voting"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    container_name: voting-db
volumes:
  pgdata:
  server_public:
